### ISSUE TITLE
problem with private youtube playlists

### ISSUE THREAD

**Issue by treaki** [dafoxia/mumble-ruby-pluginbot#154]
Hi,

we are now after a long  back and forth analyzing why a mumble-ruby-pluginbot wasn't loading a youtube playlist. After two updates using ~/src/mumble-ruby-pluginbot/scripts/updater.sh (first one disabled the bot completely, after the seconds it worked again) we had a look into ~/logs after starting the bot in debug mode and found out the youtube-dl error that the playlist could be private.

But the bot communicated only "nothing interesting here"

could you at least improve the youtube plugin to report the error output from youtube-dl instead saying things like "nothing interesting here"?

youtube-dl also has got the "Authentication Options" it would pe nice if they could be implemented in the mumble ruby pluginbot.

thanks and regards

**Comment by dafoxia** [comment]
The last weeks my free-time for programming was very limited and at the moment I can't give you any forecast when it will more time for it.
btw....
As I remember there was difficulties to parse youtube-dl error message during heavy development and message change on itself, so I gave up and planned to look in future how I can solve this.

Authentication with the bot is a bad idea because privacy problems if bot keep'd loged in, security reasons (bot run's on a machine that users can't control, but admin can and the password has to handle by plaintext).
The bot could be used as perfect man in the middle.
