### ISSUE TITLE
make sampling rate from mumble ruby configurable

### ISSUE THREAD

**Issue by netinetwalker** [dafoxia/mumble-ruby-pluginbot#24]
make sampling rate from mumble ruby configurable
default 48000 if no value is in the config ...

**Comment by dafoxia** [comment]
That is no good idea. Opus codec is optimized for 48kHz AND mumble request this sample rate.
I've not tested 44.1 kHz, maybe some clients run with it, there is no guarantee that it works for all.
It does not make sense to feed the server with stereo data because the clients it will not decode. Mono audio is due to the positional audio in part because several stereo signals can be only with some assumptions (stereo-bias) very cost intense calculated into a virtual space.
