### ISSUE TITLE
Streaming from youtube...

### ISSUE THREAD

**Issue by Natenom** [dafoxia/mumble-ruby-pluginbot#4]
An option to stream youtube urls instead of downloading would be nice. Should be possible because YT uses dash with seperate files for video/audio.

**Comment by dafoxia** [comment]
Add ability with https://github.com/dafoxia/mumble-ruby-pluginbot/commit/d29e026364e4d7895b2178d1f9becd5b85b082e5
But it is not a real stream because mpd download file complete before start playing. There is no gapless play possible.
To enable streaming set to
`@settings[:youtube_stream]= "yes"` or some other value. 
`nil` disables streaming and download titles. (standard behavior)

**Comment by dafoxia** [comment]
Currently planned no further development of this function.
